# for homework of week 2

dv = {"k": "fs:disabled_access:True", "v": ["IQUO-UECK-JHFT-VJMU", "BOEQ-SIJW-MVMI-UOQK", "HOZB-SIRY-SSPP-HPVY", "HDUA-USVQ-JVEP-DIIZ", "WKVM-YBPQ-YKBP-NYTP", "NTIM-LPLN-YKFA-EJEL", "FMSG-NFBG-UCCM-MFXH", "GLWS-NDBL-SZXM-JOOX", "RIPC-UJGD-KLZC-ULGG", "MMTW-NGOM-COAO-TCPN", "TTBI-BDYI-IDVC-RBOP", "ZCUD-KEPX-EFLA-PTFM", "NNGY-IXPK-YPSE-OIOZ", "HTHQ-UVGY-IEPL-JWPV", "YGKN-NBJQ-PHFA-TPQH", "SZJU-EWYN-KHSW-VQEE", "CCJL-MOWI-EBDC-TUPI", "HQBI-GHYV-MWOX-BOPT", "LPPO-ZJLB-XYEE-PZDQ", "WTNX-JIQU-LVKA-MDRO", "NXJO-WCKP-ZNGO-GSPM", "QARA-YRXA-IUUD-TZUY", "CDDW-AYPH-TWHN-GDSE", "BWQQ-SEJS-AQDW-OBLD", "FRDQ-VAVG-MTYG-BYCF", "FZDX-PFNS-FXCC-FJJH", "ZWBJ-QZZL-QNDR-GGQJ", "BFSR-MWCI-WPOT-IQNI", "RFFL-QUTV-BOSE-WEHM", "WHQP-KGJP-NLGK-DHGN", "XZPW-IRVO-CEDT-DLYL"], "t": "set", "ttl": -1}

s = set(dv['v'])

print(len(s))